# Psychoinformatics - Week 12 (Exercises)
by 李彥廷 (b08207008@ntu.edu.tw)

In [7]:
%config IPCompleter.greedy=True 
%matplotlib inline

from numpy import *
from matplotlib.pyplot import *
from IPython.display import *
import warnings
warnings.simplefilter('ignore', DeprecationWarning)
from sklearn import *

iris = datasets.load_iris()
X=iris.data; Y=iris.target

## 1 Performance Tuning of a Neural Net (8 points)

### 1.0 Baseline Performance
SVM can reach an classifcation accuracy ~ 8x% correct for the hard Iris problem.

In [8]:
sss=model_selection.StratifiedShuffleSplit(n_splits=5,test_size=0.1) # (45+45+45) vs. (5+5+5)
model=svm.SVC(C=10)
acc=[]
Y_test_all=[]
pred_all=[]
for train_index, test_index in sss.split(X, Y): # 5-fold cross-validation
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    model.fit(X_train[:,0:2],Y_train) #training
    pred = model.predict(X_test[:,0:2])
    acc.append(pred==Y_test) # testing
    Y_test_all.extend(Y_test)
    pred_all.extend(pred)
print(np.mean(acc))
print(metrics.confusion_matrix(Y_test_all,pred_all))

0.76
[[25  0  0]
 [ 0 16  9]
 [ 0  9 16]]


### 1.1 Tuning your ANN (4 points)
Tune your model hyperparameters (# of layers, # of units in each layer, activation function, optimizer, epochs, batch_size, etc.) to see if you can push your ANN performance up to ~9x% correct.

In [9]:
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from hyperopt import fmin, tpe, rand, hp

In [ ]:

def F(hp):
    
    model = Sequential()
    model.add(Dense(hp['hp1'],input_shape=(2,), activation='sigmoid'))
    model.add(Dense(hp['hp2'], activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


    acc=[]
    for train_index, test_index in sss.split(X, Y): # 5-fold cross-validation
        X_train, X_test = X[train_index], X[test_index]
        Y_train, Y_test = Y[train_index], Y[test_index]
        model.fit(X_train[:,0:2], to_categorical(Y_train), epochs=50, batch_size=15)
        acc.append(argmax(model.predict(X_test[:,0:2]),1)==Y_test) # testing
    return 1-np.mean(acc)

t0=time.time()
best_x = fmin(fn=F,
    space={'hp1':hp.randint('hp1', 0, 20),'hp2':hp.randint('hp2',0,20)},
    algo=tpe.suggest, # try rand.suggest
    max_evals=100)
print('Search Time:',time.time()-t0)
print(best_x)

In [10]:
model = Sequential()
model.add(Dense(10,input_shape=(2,), activation='sigmoid'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

acc=[]
Y_test_all=[]
pred_all=[]
for train_index, test_index in sss.split(X, Y): # 5-fold cross-validation
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    model.fit(X_train[:,0:2], to_categorical(Y_train), epochs=100, batch_size=5)
    pred = argmax(model.predict(X_test[:,0:2]),1)
    acc.append(pred==Y_test) # testing
    Y_test_all.extend(Y_test)
    pred_all.extend(pred)
print(np.mean(acc))
print(metrics.confusion_matrix(Y_test_all,pred_all))

Epoch 1/100
27/27 [==============================] - 0s 1ms/step - loss: 1.1406 - accuracy: 0.3333
Epoch 2/100
27/27 [==============================] - 0s 923us/step - loss: 1.1090 - accuracy: 0.2667
Epoch 3/100
27/27 [==============================] - 0s 923us/step - loss: 1.0939 - accuracy: 0.4444
Epoch 4/100
27/27 [==============================] - 0s 808us/step - loss: 1.0894 - accuracy: 0.3926
Epoch 5/100
27/27 [==============================] - 0s 809us/step - loss: 1.0796 - accuracy: 0.6519
Epoch 6/100
27/27 [==============================] - 0s 885us/step - loss: 1.0732 - accuracy: 0.6519
Epoch 7/100
27/27 [==============================] - 0s 961us/step - loss: 1.0696 - accuracy: 0.4370
Epoch 8/100
27/27 [==============================] - 0s 846us/step - loss: 1.0629 - accuracy: 0.7111
Epoch 9/100
27/27 [==============================] - 0s 966us/step - loss: 1.0546 - accuracy: 0.7111
Epoch 10/100
27/27 [==============================] - 0s 809us/step - loss: 1.0499 - accuracy

27/27 [==============================] - 0s 846us/step - loss: 0.5016 - accuracy: 0.7556
Epoch 82/100
27/27 [==============================] - 0s 962us/step - loss: 0.5034 - accuracy: 0.7556
Epoch 83/100
27/27 [==============================] - 0s 846us/step - loss: 0.4994 - accuracy: 0.7111
Epoch 84/100
27/27 [==============================] - 0s 769us/step - loss: 0.4968 - accuracy: 0.7556
Epoch 85/100
27/27 [==============================] - 0s 885us/step - loss: 0.4972 - accuracy: 0.7630
Epoch 86/100
27/27 [==============================] - 0s 923us/step - loss: 0.4939 - accuracy: 0.7556
Epoch 87/100
27/27 [==============================] - 0s 885us/step - loss: 0.4963 - accuracy: 0.7481
Epoch 88/100
27/27 [==============================] - 0s 923us/step - loss: 0.4923 - accuracy: 0.7481
Epoch 89/100
27/27 [==============================] - 0s 923us/step - loss: 0.4924 - accuracy: 0.7704
Epoch 90/100
27/27 [==============================] - 0s 923us/step - loss: 0.4898 - accuracy: 

27/27 [==============================] - 0s 884us/step - loss: 0.4412 - accuracy: 0.7852
Epoch 62/100
27/27 [==============================] - 0s 885us/step - loss: 0.4376 - accuracy: 0.7778
Epoch 63/100
27/27 [==============================] - 0s 846us/step - loss: 0.4399 - accuracy: 0.7926
Epoch 64/100
27/27 [==============================] - 0s 770us/step - loss: 0.4376 - accuracy: 0.7926
Epoch 65/100
27/27 [==============================] - 0s 769us/step - loss: 0.4395 - accuracy: 0.7926
Epoch 66/100
27/27 [==============================] - 0s 808us/step - loss: 0.4369 - accuracy: 0.7852
Epoch 67/100
27/27 [==============================] - 0s 731us/step - loss: 0.4372 - accuracy: 0.7926
Epoch 68/100
27/27 [==============================] - 0s 885us/step - loss: 0.4396 - accuracy: 0.7778
Epoch 69/100
27/27 [==============================] - 0s 808us/step - loss: 0.4366 - accuracy: 0.7852
Epoch 70/100
27/27 [==============================] - 0s 771us/step - loss: 0.4382 - accuracy: 

27/27 [==============================] - 0s 847us/step - loss: 0.4315 - accuracy: 0.7926
Epoch 42/100
27/27 [==============================] - 0s 924us/step - loss: 0.4313 - accuracy: 0.7926
Epoch 43/100
27/27 [==============================] - 0s 884us/step - loss: 0.4300 - accuracy: 0.7852
Epoch 44/100
27/27 [==============================] - 0s 770us/step - loss: 0.4336 - accuracy: 0.7778
Epoch 45/100
27/27 [==============================] - 0s 770us/step - loss: 0.4367 - accuracy: 0.7778
Epoch 46/100
27/27 [==============================] - 0s 731us/step - loss: 0.4338 - accuracy: 0.7926
Epoch 47/100
27/27 [==============================] - 0s 807us/step - loss: 0.4317 - accuracy: 0.7778
Epoch 48/100
27/27 [==============================] - 0s 846us/step - loss: 0.4339 - accuracy: 0.7852
Epoch 49/100
27/27 [==============================] - 0s 807us/step - loss: 0.4317 - accuracy: 0.7704
Epoch 50/100
27/27 [==============================] - 0s 769us/step - loss: 0.4300 - accuracy: 

27/27 [==============================] - 0s 886us/step - loss: 0.4056 - accuracy: 0.8148
Epoch 22/100
27/27 [==============================] - 0s 884us/step - loss: 0.4068 - accuracy: 0.8074
Epoch 23/100
27/27 [==============================] - 0s 923us/step - loss: 0.4064 - accuracy: 0.8148
Epoch 24/100
27/27 [==============================] - 0s 885us/step - loss: 0.4113 - accuracy: 0.7852
Epoch 25/100
27/27 [==============================] - 0s 846us/step - loss: 0.4093 - accuracy: 0.8148
Epoch 26/100
27/27 [==============================] - 0s 808us/step - loss: 0.4068 - accuracy: 0.7926
Epoch 27/100
27/27 [==============================] - 0s 808us/step - loss: 0.4060 - accuracy: 0.8000
Epoch 28/100
27/27 [==============================] - 0s 846us/step - loss: 0.4090 - accuracy: 0.8000
Epoch 29/100
27/27 [==============================] - 0s 808us/step - loss: 0.4057 - accuracy: 0.8074
Epoch 30/100
27/27 [==============================] - 0s 884us/step - loss: 0.4050 - accuracy: 

27/27 [==============================] - 0s 846us/step - loss: 0.3999 - accuracy: 0.8148
Epoch 2/100
27/27 [==============================] - 0s 923us/step - loss: 0.4012 - accuracy: 0.8000
Epoch 3/100
27/27 [==============================] - 0s 692us/step - loss: 0.3998 - accuracy: 0.8148
Epoch 4/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3980 - accuracy: 0.8222
Epoch 5/100
27/27 [==============================] - 0s 692us/step - loss: 0.3990 - accuracy: 0.8000
Epoch 6/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4021 - accuracy: 0.8074
Epoch 7/100
27/27 [==============================] - 0s 1000us/step - loss: 0.4004 - accuracy: 0.8074
Epoch 8/100
27/27 [==============================] - 0s 808us/step - loss: 0.3992 - accuracy: 0.8148
Epoch 9/100
27/27 [==============================] - 0s 885us/step - loss: 0.4065 - accuracy: 0.8000
Epoch 10/100
27/27 [==============================] - 0s 808us/step - loss: 0.4056 - accuracy: 0.8148
Epoc

27/27 [==============================] - 0s 808us/step - loss: 0.3969 - accuracy: 0.7852
Epoch 82/100
27/27 [==============================] - 0s 808us/step - loss: 0.3971 - accuracy: 0.7926
Epoch 83/100
27/27 [==============================] - 0s 770us/step - loss: 0.3982 - accuracy: 0.7926
Epoch 84/100
27/27 [==============================] - 0s 730us/step - loss: 0.4070 - accuracy: 0.7926
Epoch 85/100
27/27 [==============================] - 0s 846us/step - loss: 0.3970 - accuracy: 0.8074
Epoch 86/100
27/27 [==============================] - 0s 769us/step - loss: 0.3941 - accuracy: 0.8074
Epoch 87/100
27/27 [==============================] - 0s 769us/step - loss: 0.3940 - accuracy: 0.8074
Epoch 88/100
27/27 [==============================] - 0s 769us/step - loss: 0.4002 - accuracy: 0.7926
Epoch 89/100
27/27 [==============================] - 0s 847us/step - loss: 0.3959 - accuracy: 0.8000
Epoch 90/100
27/27 [==============================] - 0s 846us/step - loss: 0.3991 - accuracy: 

### 1.2 Is your (deep) network better than SVM? Why or why not? (4 points)

只有差不多好而已。即使使用了hyperopt來做hyperparameter tuning和反覆測試不同參數之後結果都不太理想。

我認為結果不佳的原因是只用了兩個feature，因為資訊量太少所以比較難獲得較好的結果。在這個例子裡面的input有兩個feature但output是三種，這些特徵可能難以區分出三種類別。另外特徵的特性也會影響模型的建立，若特徵本身就不是很有代表性也有可能導致效果不好，可能只達到某個極限就很難提升。若將上面的模型改成使用petal兩個特徵，馬上就可以變成0.97左右的正確率了。從圖中也可以看到sepal的數值綠色和藍色的都混在一起，若將上面的testing結果以confusion matrix表示也可以看到在第二和第三種的分辨正確率不佳。因此提升特徵的數量或是改變特徵的選取會更容易區分做到高正確率。

<img src="https://upload.wikimedia.org/wikipedia/commons/5/56/Iris_dataset_scatterplot.svg" width=40%>